# Generated by Django 3.2.6 on 2021-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=200)),
                ('max_dist', models.IntegerField()),
                ('price_range', models.IntegerField()),
                ('attendees', models.CharField(max_length=200)),
            ],
        ),
    ]
