# Generated by Django 3.2.6 on 2021-08-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='attendees',
            field=models.CharField(choices=[('1', 'Gilles'), ('2', 'Vince'), ('3', 'Sam'), ('4', 'Klaas'), ('5', 'Gaelle')], max_length=1),
        ),
    ]
