# Generated by Django 3.2.6 on 2021-08-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_resto', '0002_alter_request_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='max_dist',
            new_name='maximum_distance',
        ),
        migrations.RemoveField(
            model_name='request',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='request',
            name='price_range',
        ),
        migrations.AddField(
            model_name='request',
            name='Gaelle',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='Gilles',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='Klaas',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='Sam',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='Vince',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.CharField(choices=[('1', 'less than 10€'), ('2', 'between 11€ and 30€'), ('3', 'between 31€ and 60€'), ('4', 'over 61€')], default='', max_length=1),
        ),
    ]
