# Generated by Django 3.2.6 on 2021-08-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=1, help_text='in Km')),
                ('price', models.CharField(choices=[('1', 'less than 10€'), ('2', 'between 11€ and 30€'), ('3', 'between 31€ and 60€'), ('4', 'over 61€')], default='', max_length=1)),
                ('Gilles', models.BooleanField(default=None)),
                ('Vince', models.BooleanField(default=None)),
                ('Sam', models.BooleanField(default=None)),
                ('Klaas', models.BooleanField(default=None)),
                ('Gaelle', models.BooleanField(default=None)),
            ],
        ),
    ]
