# Generated by Django 3.2.6 on 2021-08-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='language_of_query',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('nl', 'Dutch')], default='', max_length=2),
        ),
    ]
