# Generated by Django 3.2.6 on 2021-08-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_resto', '0002_request_language_of_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='language_of_query',
            new_name='Language_of_the_request',
        ),
    ]
